### PR TITLE
Add a repo key to package.json

### PR DESCRIPTION
**Pull request by stephenmathieson**
clib-install(1) expects it.

### CODE REVIEW

**Comment by thlorenz** [comment]
But it already [contains repo info](https://github.com/thlorenz/gumbo-parser.c/blob/23532eac67cd3742f70aa3ce76ac9bf89943e91f/package.json#L36-L39).

Why do I need to duplicate this information? I believe `clib` should deduce the repo key from it instead.

**Comment by stephenmathieson** [comment]
clib is not npm, so that's not duplicate information, it's _unused_ information.

There's a huge amount of redundant information in the "repository" field (we know it's a git repo, we know it's on github, etc.), so it just doesn't make sense for clib to require all of it.

You're welcome to add support for npm-like repo definitions in clib, but ATM it doesn't support this and your package.json is wrong.

**Comment by thlorenz** [comment]
I understand, but why would clib do things differently? Most other aspects work like `npm/node`.
I generate my `package.json` via a bash script, so it'd be better IMO if things were more compatible.

**Comment by stephenmathieson** [comment]
clib(1) was originally just a hacked version of component(1).  Its package.json basically mirrors component.json, which uses `repo`.  It's different from npm because it requires different information (we're _only_ interested in `<repo owner>/<repo name>`).  This was a decision made [over a year ago](https://github.com/clibs/clib/commit/76f1e0ae59bf33fee73585255c657e8355b8a923#diff-168726dbe96b3ce427e7fedce31bb0bcR46), so we're a bit late in arguing about it.  I agree that compatibility with npm would be ideal, but it's just not currently supported (submit an issue?).

IMO, the real issue here is the filename (package.json), but it's already been accepted and changing it would require more work than it's (probably) worth.

**Comment by thlorenz** [comment]
Ok that makes sense. So what's the best solution here?
Why is the `repo` field needed, there is no registry? All is resolved from the wiki page.

If that ever changes, I believe that `clib` could add some smartness to deduce the repo field from the repository field. Does that make sense or am I missing something?

**Comment by stephenmathieson** [comment]
> Why is the repo field needed

That's a really good point; I'm not sure. We don't actually _need_ to use it, just as npm doesn't. I'll close this for now.

I agree that we could easily parse `repository` and will probably (eventually) add that in.

**Pull request closed without merging**
