### PR TITLE
Fetch and merge upstream (google/gumbo) changes

### PR DESCRIPTION
**Pull request by xSavitar**
This commits fetches, merged (while fixing all merge conflicts) from upstream.

### CODE REVIEW

**Comment by xSavitar** [comment]
@thlorenz, that's the updates from upstream. Thanks!

**Comment by thlorenz** [comment]
Awesome thanks, I assume after fixing conflicts you verified that all still compiles an works properly?

**Comment by thlorenz** [comment]
What I'm confused about is why clib related commits like this one 
fd102c5 of `package.json` appear in the merge again. I'd have thought if you just merge in upstream changes they'd be added on top of the clib commits instead of including them again.

**Comment by thlorenz** [comment]
You could also look into [`git rebase --onto`](https://womanonrails.com/git-rebase-onto), maybe that is what you actually want

**Pull request closed without merging**
